package package_specificationsEnums;

public enum AddCode {OK,NO_OBJECT,ALREADY_EXISTS,INVALIDE_PARAMETER, SUPER_USER_EXIST, 
					USER_WAS_CONNECTED, USER_WAS_DISCONNECTED, CAN_NOT_EXECUTE, USER_HAS_NOT_ACCESS}
